[2025-10-13T08:36:37.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:36:37.517+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:36:37.527+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:36:37.528+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:36:37.545+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:36:37.553+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=150) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:36:37.556+0000] {standard_task_runner.py:72} INFO - Started process 156 to run task
[2025-10-13T08:36:37.560+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpv1qut33f']
[2025-10-13T08:36:37.562+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask extract_load_group.load_transactions
[2025-10-13T08:36:37.625+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:36:37.720+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:36:37.721+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:36:41.019+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:36:41.040+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T083637, end_date=20251013T083641
[2025-10-13T08:36:41.054+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:36:41.055+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task extract_load_group.load_transactions (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 156)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:36:41.105+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:36:41.130+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:36:41.133+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:44:45.231+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:44:45.255+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:44:45.266+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:44:45.267+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:44:45.287+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:44:45.300+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=503) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:44:45.302+0000] {standard_task_runner.py:72} INFO - Started process 512 to run task
[2025-10-13T08:44:45.302+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpbr9a_7nl']
[2025-10-13T08:44:45.303+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask extract_load_group.load_transactions
[2025-10-13T08:44:45.374+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:44:45.478+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:44:45.479+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:44:56.789+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T08:44:56.790+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:44:56.802+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:44:56.802+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T084445, end_date=20251013T084456
[2025-10-13T08:44:56.834+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:44:56.855+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:44:56.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:00.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:01.009+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:54:01.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:54:01.019+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:01.033+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:54:01.042+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=691) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:01.044+0000] {standard_task_runner.py:72} INFO - Started process 697 to run task
[2025-10-13T08:54:01.044+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp8n8rm2id']
[2025-10-13T08:54:01.046+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask extract_load_group.load_transactions
[2025-10-13T08:54:01.107+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:01.204+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:54:01.205+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:54:13.203+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T08:54:13.204+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:54:13.218+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:54:13.218+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T085401, end_date=20251013T085413
[2025-10-13T08:54:13.259+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:54:13.280+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:54:13.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:05:36.787+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:05:36.811+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:05:36.822+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:05:36.823+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:05:36.842+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:05:36.852+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1023) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:05:36.854+0000] {standard_task_runner.py:72} INFO - Started process 1035 to run task
[2025-10-13T09:05:36.854+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp0f9ednp1']
[2025-10-13T09:05:36.856+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask extract_load_group.load_transactions
[2025-10-13T09:05:36.913+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:05:37.004+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:05:37.005+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:05:42.244+0000] {load.py:30} INFO - Loaded 27 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T09:05:42.245+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:05:42.258+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:05:42.259+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T090536, end_date=20251013T090542
[2025-10-13T09:05:42.296+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:05:42.314+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:05:42.316+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:15:17.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:15:17.848+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:15:17.859+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:15:17.860+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:15:17.876+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:15:17.885+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1188) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:15:17.887+0000] {standard_task_runner.py:72} INFO - Started process 1197 to run task
[2025-10-13T09:15:17.887+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpe8ygnsmm']
[2025-10-13T09:15:17.888+0000] {standard_task_runner.py:105} INFO - Job 163: Subtask extract_load_group.load_transactions
[2025-10-13T09:15:17.949+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:15:18.044+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:15:18.045+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:15:24.936+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T09:15:24.936+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:15:24.951+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:15:24.951+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T091517, end_date=20251013T091524
[2025-10-13T09:15:25.005+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:15:25.026+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:15:25.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:34.216+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:34.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:20:34.258+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:20:34.259+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:34.281+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:20:34.291+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1285) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:34.294+0000] {standard_task_runner.py:72} INFO - Started process 1295 to run task
[2025-10-13T09:20:34.295+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpf_k21jyk']
[2025-10-13T09:20:34.296+0000] {standard_task_runner.py:105} INFO - Job 172: Subtask extract_load_group.load_transactions
[2025-10-13T09:20:34.380+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:34.505+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:20:34.507+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:20:43.307+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T09:20:43.307+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:20:43.320+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:20:43.321+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T092034, end_date=20251013T092043
[2025-10-13T09:20:43.396+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:20:43.443+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:20:43.445+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:15:41.925+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:15:41.948+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:41.956+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:41.957+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:15:41.972+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:15:41.981+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:15:41.983+0000] {standard_task_runner.py:72} INFO - Started process 133 to run task
[2025-10-14T04:15:41.984+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpz4rv1ilh']
[2025-10-14T04:15:41.985+0000] {standard_task_runner.py:105} INFO - Job 243: Subtask extract_load_group.load_transactions
[2025-10-14T04:15:42.046+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:15:42.141+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:15:42.142+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:15:47.619+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:15:47.619+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:15:47.630+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:15:47.631+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T041541, end_date=20251014T041547
[2025-10-14T04:15:47.660+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:15:47.682+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:15:47.683+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:40.559+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:40.599+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:40.618+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:40.619+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:40.651+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:20:40.678+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:40.680+0000] {standard_task_runner.py:72} INFO - Started process 274 to run task
[2025-10-14T04:20:40.680+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp5sohjor1']
[2025-10-14T04:20:40.682+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask extract_load_group.load_transactions
[2025-10-14T04:20:40.753+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:40.847+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:20:40.848+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:45.049+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:20:45.050+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:45.063+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:45.063+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042040, end_date=20251014T042045
[2025-10-14T04:20:45.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:45.137+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:45.139+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:15.446+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:15.468+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:15.478+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:15.479+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:15.494+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:22:15.503+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=505) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:15.505+0000] {standard_task_runner.py:72} INFO - Started process 510 to run task
[2025-10-14T04:22:15.505+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpyog5bapv']
[2025-10-14T04:22:15.507+0000] {standard_task_runner.py:105} INFO - Job 325: Subtask extract_load_group.load_transactions
[2025-10-14T04:22:15.570+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:15.674+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:22:15.675+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:19.941+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:22:19.941+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:19.952+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:19.953+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042215, end_date=20251014T042219
[2025-10-14T04:22:20.015+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:20.030+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:08.714+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:08.739+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:08.749+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:08.750+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:08.766+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:26:08.774+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=643) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:08.776+0000] {standard_task_runner.py:72} INFO - Started process 649 to run task
[2025-10-14T04:26:08.777+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp748zanig']
[2025-10-14T04:26:08.778+0000] {standard_task_runner.py:105} INFO - Job 347: Subtask extract_load_group.load_transactions
[2025-10-14T04:26:08.846+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:08.961+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:26:08.962+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:14.934+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:26:14.934+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:14.947+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:14.947+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042608, end_date=20251014T042614
[2025-10-14T04:26:14.980+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:14.991+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:12.385+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:12.408+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:12.419+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:12.420+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:12.438+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:28:12.446+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=751) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:12.448+0000] {standard_task_runner.py:72} INFO - Started process 761 to run task
[2025-10-14T04:28:12.448+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp77sktbth']
[2025-10-14T04:28:12.450+0000] {standard_task_runner.py:105} INFO - Job 374: Subtask extract_load_group.load_transactions
[2025-10-14T04:28:12.519+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:12.620+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:28:12.621+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:17.177+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:28:17.177+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:17.188+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:17.189+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042812, end_date=20251014T042817
[2025-10-14T04:28:17.237+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:17.261+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:17.263+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:31:20.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:31:20.855+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:20.867+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:20.869+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:31:20.889+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:31:20.899+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1052) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:31:20.901+0000] {standard_task_runner.py:72} INFO - Started process 1061 to run task
[2025-10-14T04:31:20.900+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpepyesf7x']
[2025-10-14T04:31:20.902+0000] {standard_task_runner.py:105} INFO - Job 446: Subtask extract_load_group.load_transactions
[2025-10-14T04:31:20.969+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:31:21.125+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:31:21.127+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:31:25.153+0000] {load.py:30} INFO - Loaded 28 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:31:25.154+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:31:25.168+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:31:25.168+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T043120, end_date=20251014T043125
[2025-10-14T04:31:25.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:31:25.239+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:31:25.242+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
