[2025-10-13T08:36:37.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:36:37.516+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:36:37.526+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:36:37.527+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:36:37.545+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:36:37.553+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:36:37.556+0000] {standard_task_runner.py:72} INFO - Started process 157 to run task
[2025-10-13T08:36:37.556+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpbm1l7qte']
[2025-10-13T08:36:37.558+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask extract_load_group.load_transaction_items
[2025-10-13T08:36:37.626+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:36:37.725+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:36:37.726+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:36:40.982+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:36:40.999+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T083637, end_date=20251013T083640
[2025-10-13T08:36:41.010+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:36:41.011+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task extract_load_group.load_transaction_items (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 157)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:36:41.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:36:41.095+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:36:41.100+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:44:45.213+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:44:45.240+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:44:45.249+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:44:45.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:44:45.263+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:44:45.273+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:44:45.275+0000] {standard_task_runner.py:72} INFO - Started process 506 to run task
[2025-10-13T08:44:45.275+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpkcrsd7sm']
[2025-10-13T08:44:45.277+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask extract_load_group.load_transaction_items
[2025-10-13T08:44:45.348+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:44:45.451+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:44:45.452+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:44:57.144+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T08:44:57.145+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:44:57.159+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:44:57.160+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T084445, end_date=20251013T084457
[2025-10-13T08:44:57.214+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:44:57.240+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:44:57.242+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:00.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:01.008+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:54:01.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T08:54:01.019+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:01.034+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-13T08:54:01.042+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=688) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:01.044+0000] {standard_task_runner.py:72} INFO - Started process 698 to run task
[2025-10-13T08:54:01.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpogfmkkom']
[2025-10-13T08:54:01.047+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask extract_load_group.load_transaction_items
[2025-10-13T08:54:01.107+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:01.203+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T08:54:01.204+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:54:21.117+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T08:54:21.117+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:54:21.128+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:54:21.130+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T085401, end_date=20251013T085421
[2025-10-13T08:54:21.169+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:54:21.191+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:54:21.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:05:36.773+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:05:36.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:05:36.806+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:05:36.806+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:05:36.823+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:05:36.831+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1025) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:05:36.833+0000] {standard_task_runner.py:72} INFO - Started process 1029 to run task
[2025-10-13T09:05:36.835+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmphf67w9wz']
[2025-10-13T09:05:36.836+0000] {standard_task_runner.py:105} INFO - Job 150: Subtask extract_load_group.load_transaction_items
[2025-10-13T09:05:36.899+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:05:36.991+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:05:36.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:05:42.102+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T09:05:42.103+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:05:42.118+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:05:42.119+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T090536, end_date=20251013T090542
[2025-10-13T09:05:42.160+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:05:42.182+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:05:42.184+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:15:17.820+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:15:17.843+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:15:17.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:15:17.854+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:15:17.871+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:15:17.879+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1184) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:15:17.881+0000] {standard_task_runner.py:72} INFO - Started process 1195 to run task
[2025-10-13T09:15:17.881+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpjpjlkpwb']
[2025-10-13T09:15:17.882+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask extract_load_group.load_transaction_items
[2025-10-13T09:15:17.940+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:15:18.036+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:15:18.037+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:15:24.285+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T09:15:24.285+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:15:24.296+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:15:24.297+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T091517, end_date=20251013T091524
[2025-10-13T09:15:24.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:15:24.385+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:15:24.388+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:34.207+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:34.235+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:20:34.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-13T09:20:34.247+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:34.265+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-13T09:20:34.275+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1283) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:34.277+0000] {standard_task_runner.py:72} INFO - Started process 1288 to run task
[2025-10-13T09:20:34.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp9shxh4kw']
[2025-10-13T09:20:34.279+0000] {standard_task_runner.py:105} INFO - Job 171: Subtask extract_load_group.load_transaction_items
[2025-10-13T09:20:34.369+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:34.490+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-13T09:20:34.492+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:20:44.861+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-13T09:20:44.862+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:20:44.874+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:20:44.874+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251013T092034, end_date=20251013T092044
[2025-10-13T09:20:44.941+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:20:44.967+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:20:44.969+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:15:41.918+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:15:41.941+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:41.952+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:41.952+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:15:41.967+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:15:41.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=127) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:15:41.976+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2025-10-14T04:15:41.976+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp070mk44k']
[2025-10-14T04:15:41.977+0000] {standard_task_runner.py:105} INFO - Job 241: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:15:42.041+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:15:42.137+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:15:42.138+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:15:47.470+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:15:47.471+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:15:47.484+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:15:47.484+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T041541, end_date=20251014T041547
[2025-10-14T04:15:47.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:15:47.559+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:15:47.561+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:40.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:40.619+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:40.640+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:40.641+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:40.674+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:20:40.686+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:40.689+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp20tnxzin']
[2025-10-14T04:20:40.690+0000] {standard_task_runner.py:72} INFO - Started process 277 to run task
[2025-10-14T04:20:40.690+0000] {standard_task_runner.py:105} INFO - Job 267: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:20:40.759+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:40.850+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:20:40.852+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:46.489+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:20:46.490+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:46.501+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:46.501+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042040, end_date=20251014T042046
[2025-10-14T04:20:46.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:46.586+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:46.588+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:15.440+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:15.464+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:15.473+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:15.473+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:15.487+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:22:15.494+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:15.496+0000] {standard_task_runner.py:72} INFO - Started process 507 to run task
[2025-10-14T04:22:15.496+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpsc9s1lv9']
[2025-10-14T04:22:15.498+0000] {standard_task_runner.py:105} INFO - Job 324: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:22:15.563+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:15.665+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:22:15.666+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:20.460+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:22:20.461+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:20.472+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:20.472+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042215, end_date=20251014T042220
[2025-10-14T04:22:20.526+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:20.552+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:20.555+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:08.716+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:08.741+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:08.750+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:08.751+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:08.767+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:26:08.774+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=645) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:08.776+0000] {standard_task_runner.py:72} INFO - Started process 648 to run task
[2025-10-14T04:26:08.777+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpk817og69']
[2025-10-14T04:26:08.779+0000] {standard_task_runner.py:105} INFO - Job 349: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:26:08.846+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:08.962+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:26:08.963+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:14.934+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:26:14.934+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:14.947+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:14.947+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042608, end_date=20251014T042614
[2025-10-14T04:26:14.980+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:14.990+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:12.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:12.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:12.633+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:12.634+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:12.650+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:28:12.658+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=754) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:12.661+0000] {standard_task_runner.py:72} INFO - Started process 763 to run task
[2025-10-14T04:28:12.661+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpwi6in9ah']
[2025-10-14T04:28:12.663+0000] {standard_task_runner.py:105} INFO - Job 375: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:28:12.735+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:12.858+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:28:12.861+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:18.621+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:28:18.621+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:18.632+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:18.633+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042812, end_date=20251014T042818
[2025-10-14T04:28:18.693+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:18.719+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:18.721+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:31:20.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:31:20.860+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:20.875+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:20.876+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:31:20.894+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transaction_items> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:31:20.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1054) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:31:20.905+0000] {standard_task_runner.py:72} INFO - Started process 1062 to run task
[2025-10-14T04:31:20.905+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transaction_items', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpxo83yf5z']
[2025-10-14T04:31:20.906+0000] {standard_task_runner.py:105} INFO - Job 447: Subtask extract_load_group.load_transaction_items
[2025-10-14T04:31:20.975+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transaction_items scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:31:21.132+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transaction_items' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:31:21.134+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:31:24.816+0000] {load.py:30} INFO - Loaded 2000 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_transaction_items
[2025-10-14T04:31:24.817+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:31:24.831+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:31:24.832+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transaction_items, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T043120, end_date=20251014T043124
[2025-10-14T04:31:24.895+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:31:24.924+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:31:24.927+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
