[2025-10-14T04:40:30.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:40:30.518+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-10-14T04:40:30.532+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-10-14T04:40:30.533+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:40:30.553+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-12 00:00:00+00:00
[2025-10-14T04:40:30.563+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1644) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:40:30.565+0000] {standard_task_runner.py:72} INFO - Started process 1653 to run task
[2025-10-14T04:40:30.566+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-12T00:00:00+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmphm2bbf2f']
[2025-10-14T04:40:30.567+0000] {standard_task_runner.py:105} INFO - Job 578: Subtask extract_load_group.load_products
[2025-10-14T04:40:30.629+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-12T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:40:30.777+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T00:00:00+00:00'
[2025-10-14T04:40:30.778+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:40:40.462+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:40:40.462+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:40:40.479+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:40:40.480+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-12T00:00:00+00:00, execution_date=20250912T000000, start_date=20251014T044030, end_date=20251014T044040
[2025-10-14T04:40:40.541+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:40:40.565+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:40:40.567+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:40:40.569+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
